<?php
namespace App\Services;
use App\Events\TablePlayEvent;
use App\Models\{Bill,Payment,TableSession};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class BillingService {
 public function generate(TableSession $session,int $userId,float $discount=0): Bill { return DB::transaction(function() use($session,$userId,$discount){ $session=TableSession::lockForUpdate()->findOrFail($session->id); if($session->bill)return $session->bill; $orders=$session->orders()->whereNotIn('status',['cancelled','rejected'])->get(); $subtotal=(float)$orders->sum('subtotal');$tax=(float)$orders->sum('tax_amount'); $bill=Bill::create(['bill_number'=>'PENDING','table_session_id'=>$session->id,'subtotal'=>$subtotal,'tax_amount'=>$tax,'discount_amount'=>$discount,'grand_total'=>max(0,$subtotal+$tax-$discount),'generated_by'=>$userId,'generated_at'=>now()]); $bill->update(['bill_number'=>NumberService::make('BILL',$bill->id)]);$session->update(['status'=>'billing']);DB::afterCommit(fn()=>TablePlayEvent::dispatch('BillGenerated',['bill'=>$bill->toArray()],['table.'.$session->dining_table_id,'counter']));return $bill; }); }
 public function payCash(Bill $bill,int $userId,float $received,?string $note=null): Payment { return DB::transaction(function() use($bill,$userId,$received,$note){$bill=Bill::lockForUpdate()->findOrFail($bill->id);if($bill->payment_status!=='unpaid')throw ValidationException::withMessages(['bill'=>'Bill is not unpaid.']);if($received<(float)$bill->grand_total)throw ValidationException::withMessages(['received_amount'=>'Insufficient cash.']);$payment=Payment::create(['bill_id'=>$bill->id,'payment_number'=>'PENDING','method'=>'cash','amount'=>$bill->grand_total,'received_amount'=>$received,'change_amount'=>$received-(float)$bill->grand_total,'received_by'=>$userId,'paid_at'=>now(),'note'=>$note]);$payment->update(['payment_number'=>NumberService::make('PAY',$payment->id)]);$bill->update(['payment_status'=>'paid','paid_at'=>now()]);$session=$bill->tableSession;$session->update(['status'=>'closed','closed_by'=>$userId,'closed_at'=>now()]);$session->diningTable()->update(['status'=>'available']);app(GameAccessService::class)->stopAll($session,$userId);DB::afterCommit(fn()=>TablePlayEvent::dispatch('TableSessionClosed',['table_session_id'=>$session->id,'payment'=>$payment->toArray()],['table.'.$session->dining_table_id,'counter']));return $payment;}); }
}
