<?php
namespace App\Http\Controllers\Api;
use App\Events\TablePlayEvent;
use App\Http\Controllers\Controller;
use App\Models\{Category,Game,GameResult,MenuItem,Order,OrderItem,OrderStatusLog,RestaurantSetting,ServiceRequest,TableSession};
use App\Services\{EntitlementService,GameAccessService,NumberService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class TabletController extends Controller {
 public function branding(){return RestaurantSetting::first();}
 private function pairing(Request $r){$pairing=$r->attributes->get('device')->pairings()->where('is_active',true)->with('diningTable')->firstOrFail();app(EntitlementService::class)->assertCustomerAppAccess($pairing);return $pairing;}
 private function session(Request $r){return TableSession::where('dining_table_id',$this->pairing($r)->dining_table_id)->whereIn('status',['open','billing'])->latest('id')->firstOrFail();}
 public function currentSession(Request $r){return $this->session($r)->load('diningTable','orders.items','serviceRequests','bill');}
 public function snapshot(Request $r,GameAccessService $service){$session=$this->session($r)->load('diningTable','orders.items','serviceRequests','bill');return ['session'=>$session,'orders'=>$session->orders->sortByDesc('id')->values(),'game'=>$service->state($session)];}
 public function menu(Request $r){$this->pairing($r);return Category::where('is_active',true)->orderBy('sort_order')->with(['menuItems'=>fn($q)=>$q->where('is_active',true)->where('is_available',true)->orderBy('name')])->get();}
 public function openSession(Request $r){app(EntitlementService::class)->assertCanOpenSession();$data=$r->validate(['guest_count'=>'required|integer|min:1|max:50']);$table=$this->pairing($r)->diningTable;return DB::transaction(function()use($table,$data){$table=$table->newQuery()->lockForUpdate()->findOrFail($table->id);abort_if(TableSession::where('dining_table_id',$table->id)->whereIn('status',['open','billing'])->exists(),422,'Table already has an active session.');$s=TableSession::create(['session_code'=>'PENDING','dining_table_id'=>$table->id,'guest_count'=>$data['guest_count'],'opened_at'=>now(),'status'=>'open']);$s->update(['session_code'=>NumberService::make('SES',$s->id)]);$table->update(['status'=>'occupied']);return response()->json($s,201);});}
 public function placeOrder(Request $r){$data=$r->validate(['items'=>'required|array|min:1','items.*.menu_item_id'=>'required|integer|exists:menu_items,id','items.*.quantity'=>'required|integer|min:1|max:50','items.*.special_instruction'=>'nullable|string|max:500','customer_note'=>'nullable|string|max:1000']);$session=$this->session($r);return DB::transaction(function()use($data,$session){$session=TableSession::lockForUpdate()->findOrFail($session->id);abort_unless($session->status==='open',422);$ids=collect($data['items'])->pluck('menu_item_id');$menu=MenuItem::whereIn('id',$ids)->where('is_active',true)->where('is_available',true)->get()->keyBy('id');abort_unless($menu->count()===$ids->unique()->count(),422,'An item is unavailable.');$subtotal=collect($data['items'])->sum(fn($i)=>(float)$menu[$i['menu_item_id']]->price*$i['quantity']);$taxRate=(float)(RestaurantSetting::value('tax_rate')??0);$tax=round($subtotal*$taxRate/100,2);$order=Order::create(['order_number'=>'PENDING','table_session_id'=>$session->id,'order_sequence'=>$session->orders()->count()+1,'status'=>'pending','subtotal'=>$subtotal,'tax_amount'=>$tax,'discount_amount'=>0,'total_amount'=>$subtotal+$tax,'customer_note'=>$data['customer_note']??null]);$order->update(['order_number'=>NumberService::make('ORD',$order->id)]);foreach($data['items'] as $i){$m=$menu[$i['menu_item_id']];OrderItem::create(['order_id'=>$order->id,'menu_item_id'=>$m->id,'item_name_snapshot'=>$m->name,'unit_price'=>$m->price,'quantity'=>$i['quantity'],'line_total'=>(float)$m->price*$i['quantity'],'special_instruction'=>$i['special_instruction']??null,'status'=>'pending']);}OrderStatusLog::create(['order_id'=>$order->id,'to_status'=>'pending']);$order->load('items');DB::afterCommit(fn()=>TablePlayEvent::dispatch('OrderPlaced',['order'=>$order->toArray()],['table.'.$session->dining_table_id,'counter']));return response()->json($order,201);});}
 public function showOrder(Request $r,Order $order){abort_unless($order->table_session_id===$this->session($r)->id,404);return $order->load('items','statusLogs');}
 public function tableOrders(Request $r){return $this->session($r)->orders()->with('items')->latest()->get();}
 public function serviceRequest(Request $r){$data=$r->validate(['request_type'=>'required|in:call_waiter,water,bill,other','message'=>'nullable|string|max:500']);$session=$this->session($r);$request=ServiceRequest::create($data+['table_session_id'=>$session->id,'status'=>'pending']);TablePlayEvent::dispatch('ServiceRequestCreated',['service_request'=>$request->toArray()],['table.'.$session->dining_table_id,'counter']);return response()->json($request,201);}
 public function gameAccess(Request $r,GameAccessService $service){app(EntitlementService::class)->assertFeature('games');return $service->state($this->session($r));}
 public function games(Request $r){$this->pairing($r);app(EntitlementService::class)->assertFeature('games');return Game::where('is_active',true)->orderBy('sort_order')->get();}
 public function gameResult(Request $r){$this->pairing($r);app(EntitlementService::class)->assertFeature('games');$data=$r->validate(['game_id'=>['required',Rule::exists('games','id')->where(fn($q)=>$q->where('is_active',true))],'player_name'=>'nullable|string|max:100','player_position'=>'nullable|integer|min:1|max:4','score'=>'required|integer|min:0','duration_seconds'=>'nullable|integer|min:0']);$state=app(GameAccessService::class)->state($this->session($r));abort_unless($state['unlocked'],403,'Games are locked.');return response()->json(GameResult::create($data+['game_session_id'=>$state['session']->id,'played_at'=>now()]),201);}
}
