<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TablePlay.Uninstaller</AssemblyName>
    <RootNamespace>TablePlay.Uninstaller</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.5.6</Version>
  </PropertyGroup>
</Project>
