@extends('layouts.app')
@section('title', 'Restaurant settings')
@section('eyebrow', 'Configuration')
@section('page-title', 'Restaurant settings')

@section('content')
<div class="page-heading"><div><h2>Identity & operating rules</h2><p>These settings drive staff screens, receipts, tax calculation, device health, and the server-controlled game timer.</p></div><div class="page-heading__actions"><a class="button button--secondary" href="{{ route('admin.system') }}"><x-icon name="health" :size="17" /> View system health</a></div></div>
<form method="post" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
    <div class="content-grid content-grid--2">
        <div class="stack">
            <section class="card"><div class="card__header"><div><h2>Restaurant identity</h2><p>Brand details shown throughout TablePlay</p></div><img src="{{ $settings?->restaurant_logo_url ?: '/brand/tableplay-mark.svg' }}" width="40" height="40" alt=""></div><div class="card__body"><div class="form-grid"><label class="field field--full">Restaurant name<input name="restaurant_name" value="{{ old('restaurant_name',$settings?->restaurant_name) }}" required></label><label class="field field--full">Tagline<input name="tagline" maxlength="120" value="{{ old('tagline',$settings?->tagline) }}" placeholder="Dine. Play. Delight."></label><label class="field">Phone<input name="phone" value="{{ old('phone',$settings?->phone) }}" inputmode="tel"></label><label class="field">Email<input type="email" name="email" value="{{ old('email',$settings?->email) }}"></label><label class="field">GSTIN / tax ID<input name="gstin" maxlength="30" value="{{ old('gstin',$settings?->gstin) }}"></label><label class="field">Primary accent<input type="color" name="brand_color" value="{{ old('brand_color',$settings?->brand_color ?: '#ef6a3a') }}" required></label><label class="field">Secondary colour<input type="color" name="secondary_color" value="{{ old('secondary_color',$settings?->secondary_color ?: '#123c35') }}" required></label><label class="field field--full">Address<textarea name="address" placeholder="Printed on customer receipts">{{ old('address',$settings?->address) }}</textarea></label></div></div></section>
            <section class="card"><div class="card__header"><div><h2>Two simple logos</h2><p>These two files automatically brand the complete TablePlay system</p></div><x-icon name="settings" /></div><div class="card__body"><div class="form-grid">
                <label class="field"><span>Restaurant logo</span>@if($settings?->restaurant_logo_url)<img src="{{ $settings->restaurant_logo_url }}" alt="Restaurant logo preview" style="width:88px;height:88px;object-fit:contain;border-radius:14px;background:#f4f6f8;padding:6px;margin:6px 0">@endif<input type="file" name="restaurant_logo" accept="image/png,image/jpeg,image/webp"><small>Used on the portal, restaurant header, menu and receipts.</small></label>
                <label class="field"><span>TablePlay app logo</span>@if($settings?->app_logo_url)<img src="{{ $settings->app_logo_url }}" alt="App logo preview" style="width:88px;height:88px;object-fit:contain;border-radius:14px;background:#f4f6f8;padding:6px;margin:6px 0">@endif<input type="file" name="app_logo" accept="image/png,image/jpeg,image/webp"><small>Used for Customer, Staff, system branding and browser favicon.</small></label>
            </div><p class="form-hint">Recommended: square transparent PNG logos of at least 512×512. App launcher and EXE icons still require a signed application rebuild.</p></div></section>
            <section class="card"><div class="card__header"><div><h2>Receipt</h2><p>Customer-facing footer and business information</p></div><x-icon name="receipt" /></div><div class="card__body"><label class="field">Receipt footer<textarea name="receipt_footer" placeholder="Thank you for dining with us.">{{ old('receipt_footer',$settings?->receipt_footer) }}</textarea><small>Keep this short enough for an 80 mm receipt printer.</small></label></div></section>
        </div>
        <div class="stack">
            <section class="card"><div class="card__header"><div><h2>Tax & currency</h2><p>Applied when customers place orders</p></div></div><div class="card__body"><div class="form-grid form-grid--3"><label class="field">Currency<input name="currency" maxlength="3" value="{{ old('currency',$settings?->currency ?: 'INR') }}" required></label><label class="field">Tax label<input name="tax_name" value="{{ old('tax_name',$settings?->tax_name ?: 'GST') }}" required></label><label class="field">Tax rate<div class="input-group"><input type="number" step="0.01" min="0" max="100" name="tax_rate" value="{{ old('tax_rate',$settings?->tax_rate ?: 0) }}" required><span class="input-group__suffix">%</span></div></label></div></div></section>
            <section class="card"><div class="card__header"><div><h2>Operations</h2><p>Local timing and monitoring thresholds</p></div><x-icon name="settings" /></div><div class="card__body"><div class="form-grid"><label class="field field--full">Timezone<select name="timezone" required>@foreach(['Asia/Kolkata'=>'India Standard Time','UTC'=>'UTC','Asia/Dubai'=>'Dubai','Asia/Singapore'=>'Singapore','Europe/London'=>'London','America/New_York'=>'New York'] as $zone=>$label)<option value="{{ $zone }}" @selected(old('timezone',$settings?->timezone ?: 'Asia/Kolkata')===$zone)>{{ $label }} ({{ $zone }})</option>@endforeach</select></label><label class="field">Kitchen refresh<div class="input-group"><input type="number" min="2" max="30" name="kitchen_refresh_seconds" value="{{ old('kitchen_refresh_seconds',$settings?->kitchen_refresh_seconds ?: 4) }}" required><span class="input-group__suffix">sec</span></div></label><label class="field">Offline threshold<div class="input-group"><input type="number" min="1" max="60" name="device_offline_minutes" value="{{ old('device_offline_minutes',$settings?->device_offline_minutes ?: 5) }}" required><span class="input-group__suffix">min</span></div></label></div></div></section>
            <section class="card"><div class="card__header"><div><h2>Gaming access</h2><p>Server-enforced unlock duration after confirmation</p></div><x-icon name="game" /></div><div class="card__body"><label class="field">Default game session<div class="input-group"><input type="number" min="1" max="240" name="game_duration_minutes" value="{{ old('game_duration_minutes',$settings?->game_duration_minutes ?: 60) }}" required><span class="input-group__suffix">min</span></div><small>Confirming an additional order restarts this timer. Billing or closing the table locks games immediately.</small></label></div></section>
        </div>
    </div>
    <div class="settings-savebar"><span><strong>Configuration changes are audited.</strong><small>Existing open orders keep their saved price and tax snapshots.</small></span><button class="button button--accent" type="submit"><x-icon name="check" :size="17" /> Save all settings</button></div>
</form>
@endsection
