@extends('layouts.app')
@section('title', 'Setup guide')
@section('eyebrow', 'Guided onboarding')
@section('page-title', 'Restaurant setup')

@section('content')
@php
    $customerAppEnabled = (bool) data_get($licenseState, 'licensed', false) && (bool) data_get($licenseState, 'features.customer_app', false);
    $tabletLimit = data_get($licenseState, 'limits.paired_tables');
    $pairedTablets = (int) data_get($licenseState, 'usage.paired_tables', 0);
    $pairingSlotAvailable = $customerAppEnabled && ($tabletLimit === null || $pairedTablets < (int) $tabletLimit);
@endphp
@unless($pairingSlotAvailable)
<section class="card" style="margin-bottom:16px;border-color:var(--warning)"><div class="card__body"><strong>{{ $customerAppEnabled ? 'Your plan tablet limit is full.' : 'Customer tablets are not included in the current plan.' }}</strong> <span class="muted">{{ $customerAppEnabled ? 'Unpair an unused tablet or upgrade before generating another pairing QR.' : 'Use the Waiter app for table orders, or upgrade before installing and pairing Customer tablets.' }}</span> <a href="{{ route('admin.license.index') }}">View licence and plan</a></div></section>
@endunless
<section class="setup-hero card card--accent"><div><span class="eyebrow">{{ $completed }} of {{ $total }} checks complete</span><h2>{{ $settings->setup_completed_at ? 'TablePlay is configured' : 'Let’s prepare your restaurant' }}</h2><p>Complete each card in order. Your progress is saved automatically, so you can safely leave and return.</p><div class="setup-progress"><i style="width:{{ $percent }}%"></i></div></div><strong>{{ $percent }}%</strong></section>

<nav class="setup-steps" aria-label="Setup progress">@foreach($steps as $number=>$step)<a href="#setup-{{ $step['key'] }}" class="{{ $step['complete'] ? 'is-complete' : '' }}"><span>{{ $step['complete'] ? '✓' : $number+1 }}</span><small>{{ $step['label'] }}</small></a>@endforeach</nav>

<div class="setup-grid">
    <section class="card setup-card" id="setup-identity"><header><span class="setup-card__number">1</span><div><h2>Restaurant identity</h2><p>One form brands the portal, apps, favicon, menu, and receipts.</p></div><x-status :value="$steps[0]['complete'] ? 'completed' : 'pending'" /></header><form class="card__body" method="post" enctype="multipart/form-data" action="{{ route('admin.setup.identity') }}">@csrf @method('PUT')<div class="form-grid"><label class="field field--full">Restaurant name<input name="restaurant_name" value="{{ old('restaurant_name',$settings->restaurant_name) }}" required></label><label class="field">Tagline<input name="tagline" value="{{ old('tagline',$settings->tagline) }}"></label><label class="field">Phone<input name="phone" value="{{ old('phone',$settings->phone) }}"></label><label class="field">Email<input type="email" name="email" value="{{ old('email',$settings->email) }}"></label><label class="field field--full">Address<textarea name="address">{{ old('address',$settings->address) }}</textarea></label><label class="field">Restaurant logo<input type="file" name="restaurant_logo" accept="image/png,image/jpeg,image/webp"><small>Shown to guests and on receipts.</small></label><label class="field">TablePlay app logo<input type="file" name="app_logo" accept="image/png,image/jpeg,image/webp"><small>Shown in both apps, the system, and favicon.</small></label><label class="field">Currency<input name="currency" maxlength="3" value="{{ old('currency',$settings->currency ?: 'INR') }}" required></label><label class="field">Tax name<input name="tax_name" value="{{ old('tax_name',$settings->tax_name ?: 'GST') }}" required></label><label class="field">Tax rate<input type="number" name="tax_rate" min="0" max="100" step="0.01" value="{{ old('tax_rate',$settings->tax_rate ?: 0) }}" required></label></div><div class="form-actions"><button class="button" type="submit"><x-icon name="check" :size="16" /> Save identity and branding</button></div></form></section>

    <section class="card setup-card" id="setup-health"><header><span class="setup-card__number">2</span><div><h2>Local server health</h2><p>Core services required during restaurant operation.</p></div><x-status :value="$health['overall']" /></header><div class="card__body setup-health">@foreach($health['checks'] as $check)<div><x-icon :name="$check['status']==='healthy'?'check':'help'" :size="17" /><span><strong>{{ $check['label'] }}</strong><small>{{ $check['message'] }}</small></span><x-status :value="$check['status']" /></div>@endforeach</div><div class="card__footer"><a class="button button--secondary button--small" href="{{ route('admin.system') }}">Open full diagnostics</a></div></section>

    <section class="card setup-card" id="setup-tables"><header><span class="setup-card__number">3</span><div><h2>Create dining tables</h2><p>Existing tables are preserved; only missing codes are added.</p></div><x-status :value="$steps[2]['complete'] ? 'completed' : 'pending'" /></header><form class="card__body" method="post" action="{{ route('admin.setup.tables') }}">@csrf<div class="form-grid"><label class="field">Number of tables<input type="number" name="count" min="1" max="100" value="{{ max(10,$tables->count()) }}" required></label><label class="field">Default seats<input type="number" name="capacity" min="1" max="50" value="4" required></label></div><div class="form-actions"><span class="muted">Creates T01, T02, T03…</span><button class="button" type="submit">Create missing tables</button></div></form><div class="setup-chip-row">@foreach($tables as $table)<span>{{ $table->table_code }} @if($table->pairings->count())<i>Paired</i>@endif</span>@endforeach</div></section>

    <section class="card setup-card" id="setup-staff"><header><span class="setup-card__number">4</span><div><h2>Create staff accounts</h2><p>Add Counter, Kitchen, and Waiter logins.</p></div><x-status :value="$steps[3]['complete'] ? 'completed' : 'pending'" /></header><form class="card__body" method="post" action="{{ route('admin.staff.store') }}">@csrf<div class="form-grid"><label class="field">Role<select name="role_id" required>@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->display_name }}</option>@endforeach</select></label><label class="field">Name<input name="name" maxlength="255" required></label><label class="field">Username<input name="username" minlength="3" maxlength="100" pattern="[A-Za-z0-9._-]+" required></label><label class="field">Password<span class="secret-input"><input id="setup-staff-password" type="password" name="password" minlength="8" maxlength="255" autocomplete="new-password" required><button type="button" data-secret-toggle aria-controls="setup-staff-password" aria-label="Show password" title="Show password"><span data-secret-label>Show</span></button></span></label></div><div class="form-actions"><button class="button" type="submit"><x-icon name="plus" :size="16" /> Add staff account</button></div></form><div class="setup-chip-row">@foreach($staff as $user)<span>{{ $user->name }} <i>{{ $user->role->display_name }}</i></span>@endforeach</div></section>

    <section class="card setup-card setup-card--wide" id="setup-apps"><header><span class="setup-card__number">5</span><div><h2>Install TablePlay applications</h2><p>Download over the local network—no internet is required.</p></div><x-status :value="$steps[4]['complete'] ? 'completed' : 'pending'" /></header><div class="card__body setup-downloads"><article><x-icon name="counter" :size="26" /><div><strong>Staff Desktop</strong><small>Admin, Counter, Kitchen, and Waiter</small></div><a class="button" href="/api/v1/app-updates/download/staff-windows">Download Windows</a></article><article><x-icon name="device" :size="26" /><div><strong>Customer Table App</strong><small>{{ $customerAppEnabled ? 'Android ordering, service, and games' : 'Not included in the current plan' }}</small></div><a class="button" href="{{ $customerAppEnabled ? '/api/v1/app-updates/download/customer-android' : route('admin.license.index') }}">{{ $customerAppEnabled ? 'Download Android' : 'View plans' }}</a></article></div></section>

    <section class="card setup-card setup-card--wide" id="setup-pairing"><header><span class="setup-card__number">6</span><div><h2>Pair the first customer tablet</h2><p>{{ $pairingSlotAvailable ? 'Select a table, create a secure QR, then scan it in the Customer app.' : ($customerAppEnabled ? 'The current plan tablet limit is full.' : 'Customer tablet pairing is not included in this plan.') }}</p></div><x-status :value="$steps[5]['complete'] ? 'completed' : 'pending'" /></header>@if($pairingSlotAvailable)<div class="card__body pairing-workspace"><div><h3>Choose an unpaired table</h3><div class="pairing-table-grid">@forelse($tables->filter(fn($table)=>!$table->pairings->count()) as $table)<form method="post" action="{{ route('admin.setup.pairing',$table) }}">@csrf<button type="submit"><strong>{{ $table->table_code }}</strong><small>{{ $table->table_name }}</small><x-icon name="arrow" :size="15" /></button></form>@empty<p class="muted">Every active table already has a tablet.</p>@endforelse</div></div>@if($pairingPayload)<div class="pairing-qr-card"><div class="pairing-qr-frame"><canvas width="240" height="240" data-pairing-qr data-payload="{{ json_encode($pairingPayload) }}"></canvas></div><div><span class="eyebrow">Ready to scan</span><h3>{{ $pairingPayload['table_code'] }} &middot; {{ $pairingPayload['table_name'] }}</h3><p>Customer app → Set up this table → Scan pairing QR. This code expires {{ \Illuminate\Support\Carbon::parse($pairingPayload['expires_at'])->diffForHumans() }} and works once.</p></div></div>@else<div class="pairing-placeholder"><x-icon name="device" :size="34" /><strong>Select a table to generate its QR</strong><p>The secure code expires after 15 minutes.</p></div>@endif</div>@else<div class="card__body"><div class="modal-note"><x-icon name="license" :size="16" /><span>{{ $customerAppEnabled ? 'Unpair an unused tablet or upgrade for more tables.' : 'Upgrade to Best, Pro, or Premium to add customer tablets.' }}</span></div><div class="form-actions"><a class="button" href="{{ route('admin.license.index') }}">View licence and plan</a></div></div>@endif</section>

    <section class="card setup-card" id="setup-test"><header><span class="setup-card__number">7</span><div><h2>Run one test order</h2><p>Verify the complete restaurant workflow.</p></div><x-status :value="$steps[6]['complete'] ? 'completed' : 'pending'" /></header><div class="card__body checklist"><span><x-icon name="check" :size="16" /> {{ $customerAppEnabled ? 'Open a visit from the paired Customer tablet.' : 'Open a visit from the Waiter app.' }}</span><span><x-icon name="check" :size="16" /> Place an order and confirm it at Counter.</span><span><x-icon name="check" :size="16" /> Move it through Kitchen{{ data_get($licenseState, 'features.games', false) ? ' and verify game access.' : '.' }}</span><span><x-icon name="check" :size="16" /> Generate the bill, pay cash, and close the table.</span></div></section>

    <section class="card setup-card setup-finish"><header><span class="setup-card__number"><x-icon name="setup" :size="20" /></span><div><h2>Finish setup</h2><p>{{ $ready ? 'Required configuration is complete.' : 'Finish identity, server, tables, staff, and app checks first.' }}</p></div></header><div class="card__body"><form method="post" action="{{ route('admin.setup.complete') }}">@csrf<button class="button button--accent button--block" type="submit" @disabled(!$ready)><x-icon name="check" :size="17" /> Mark restaurant ready</button></form></div></section>
    <section class="card setup-card setup-card--wide" id="setup-staff-connection"><header><span class="setup-card__number">5A</span><div><h2>Connect Staff Android</h2><p>This QR configures only the restaurant server. Staff still sign in with their own credentials.</p></div><x-icon name="device" :size="21" /></header><div class="card__body pairing-workspace"><div><h3>Staff server connection</h3><p class="muted">Connect the phone to restaurant Wi-Fi, open Staff App, then choose <strong>Scan restaurant server QR</strong>.</p><form method="post" action="{{ route('admin.setup.staff-connection') }}">@csrf<button class="button" type="submit"><x-icon name="setup" :size="16" /> Generate Staff Connection QR</button></form></div>@if($staffConnectionPayload)<div class="pairing-qr-card"><div class="pairing-qr-frame"><canvas width="240" height="240" data-connection-qr data-payload="{{ json_encode($staffConnectionPayload) }}"></canvas></div><div><span class="eyebrow">Staff connection only</span><h3>{{ $staffConnectionPayload['server_name'] }}</h3><p>{{ $staffConnectionPayload['api_base_url'] }}</p><button class="button button--secondary button--small" type="button" data-copy-payload="{{ json_encode($staffConnectionPayload) }}">Copy setup code</button></div></div>@else<div class="pairing-placeholder"><x-icon name="device" :size="34" /><strong>Generate a Staff server QR</strong><p>No table assignment or staff credentials are stored in this QR.</p></div>@endif</div></section>
</div>
@endsection
