@extends('layouts.app')
@section('title','TablePlay Cloud')
@section('eyebrow','Platform operations')
@section('page-title','TablePlay Cloud')
@section('content')
<div class="page-heading"><div><h2>Restaurants, subscriptions and installations</h2><p>The private Ed25519 signing key remains only on this Cloud server.</p></div><div class="page-heading__actions"><a class="button button--secondary" href="{{ route('superadmin.index') }}">Plan catalogue</a></div></div>

@unless($signingReady)<section class="card" style="border-color:#fecaca;margin-bottom:18px"><div class="card__body"><strong>Licence signing is not configured.</strong><p>Run <code>php artisan tableplay:license-keypair</code>, save both keys on Cloud, and include only the public key in restaurant installers.</p></div></section>@endunless

@if(session('issued_license_key'))
<section class="card" style="border-color:#86efac;margin-bottom:18px"><div class="card__header"><div><h2>New activation key</h2><p>Copy it now. Only its SHA-256 hash is stored.</p></div></div><div class="card__body"><code style="display:block;padding:16px;background:#0f172a;color:#fff;border-radius:10px;font-size:17px;word-break:break-all">{{ session('issued_license_key') }}</code></div></section>
@endif

<section class="card"><div class="card__header"><div><h2>Add restaurant</h2><p>Create the customer, subscription and first activation key together</p></div><x-icon name="plus" /></div><form class="card__body" method="post" action="{{ route('superadmin.cloud.restaurants.store') }}">@csrf<div class="form-grid form-grid--3"><label class="field">Restaurant name<input name="name" required></label><label class="field">Owner name<input name="owner_name"></label><label class="field">Owner email<input type="email" name="owner_email"></label><label class="field">Owner phone<input name="owner_phone"></label><label class="field">Plan<select name="commercial_plan_id" required>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }} · {{ $plan->max_paired_tables===null?'Unlimited':$plan->max_paired_tables.' tablets' }}</option>@endforeach</select></label><label class="field">Duration days<input type="number" name="duration_days" min="1" max="3650" value="365"></label></div><div class="form-actions"><button class="button" type="submit">Create restaurant and key</button></div></form></section>

<section class="card" style="margin-top:18px"><div class="card__header"><div><h2>Customer installations</h2><p>Renew, upgrade, deactivate or transfer without changing restaurant data.</p></div></div><div class="card__body">@forelse($restaurants as $restaurant)<article style="padding:16px 0;border-bottom:1px solid var(--line)"><div class="page-heading" style="margin-bottom:12px"><div><h3>{{ $restaurant->name }}</h3><p>{{ $restaurant->owner_email ?: 'No owner email' }} · {{ $restaurant->restaurant_uuid }}</p></div><x-status :value="$restaurant->status" /></div>@foreach($restaurant->subscriptions as $subscription)<div class="table-wrap"><table class="data-table"><thead><tr><th>Plan</th><th>Reference</th><th>Expires</th><th>Installations</th><th>Actions</th></tr></thead><tbody><tr><td>{{ $subscription->plan->name }}</td><td>{{ $subscription->license_reference }}</td><td>{{ $subscription->expires_at?->format('d M Y') ?? 'No expiry' }}</td><td>{{ $subscription->installations->where('status','active')->count() }} / {{ $subscription->max_installations }}</td><td><form method="post" action="{{ route('superadmin.cloud.keys.issue',$subscription) }}" style="display:inline">@csrf<button class="button button--secondary button--small">New key</button></form></td></tr>@foreach($subscription->installations as $installation)<tr><td colspan="2"><strong>{{ $installation->device_name }}</strong><br><small>{{ $installation->installation_uuid }}</small></td><td><x-status :value="$installation->status" /></td><td>{{ $installation->last_seen_at?->diffForHumans() ?? 'Never synced' }}</td><td><a class="button button--secondary button--small" href="{{ route('superadmin.cloud.installations.license',$installation) }}">Offline licence</a> <form method="post" action="{{ route('superadmin.cloud.installations.transfer',$installation) }}" style="display:inline" data-confirm="Transfer this licence to a replacement server?">@csrf<button class="button button--secondary button--small">Transfer</button></form></td></tr>@endforeach</tbody></table></div><form class="form-grid form-grid--3" method="post" action="{{ route('superadmin.cloud.subscriptions.renew',$subscription) }}" style="margin-top:12px">@csrf<label class="field">Renew/upgrade<select name="commercial_plan_id">@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected($plan->id===$subscription->commercial_plan_id)>{{ $plan->name }}</option>@endforeach</select></label><label class="field">Days<input type="number" name="duration_days" value="365" min="1" max="3650"></label><div class="field" style="justify-content:end"><button class="button" type="submit">Apply renewal</button></div></form>@endforeach</article>@empty<x-empty-state icon="tables" title="No restaurants have been created" />@endforelse</div></section>
@endsection
