@extends('layouts.app')
@section('title','Commercial Operations')
@section('eyebrow','TablePlay Cloud')
@section('page-title','Restaurant Customers')
@section('content')
<div class="page-heading cloud-page-heading"><div><span class="superadmin-kicker"><x-icon name="team" size="15" /> Customer operations</span><h2>Restaurant customer workspace</h2><p>Subscriptions, licensing, billing and customer health for every independent TablePlay restaurant.</p></div><div class="page-heading__actions"><a class="button button--secondary" href="{{ route('superadmin.cloud.export') }}"><x-icon name="download" size="16" /> Export</a><button class="button button--secondary" type="button" data-dialog-open="commercial-settings"><x-icon name="settings" size="16" /> Billing setup</button><a class="button button--secondary" href="{{ route('superadmin.index') }}"><x-icon name="license" size="16" /> Plans</a><button class="button button--accent" type="button" data-dialog-open="new-customer"><x-icon name="plus" size="16" /> Add customer</button></div></div>

@unless($signingReady)<div class="alert alert--danger cloud-signing-alert"><span class="cloud-signing-alert__icon"><x-icon name="license" size="18" /></span><div><strong>Complete license signing setup</strong><p>Production activation keys remain disabled until the Cloud signing keypair is configured.</p></div><span class="status-badge status-badge--disabled"><i></i>Action required</span></div>@endunless
@if(session('issued_license_key'))<section class="activation-key-card"><div><span>One-time activation key</span><strong>Copy this key now. Only its secure hash is stored.</strong></div><code>{{ session('issued_license_key') }}</code></section>@endif

<section class="card" style="margin-bottom:18px"><div class="card__header"><div><h2>Offline activation exchange</h2><p>Verify a restaurant request, assign its subscription and generate the exact signed licence file for USB transfer.</p></div><x-icon name="license" /></div><div class="card__body"><div class="billing-split"><form method="post" action="{{ route('superadmin.cloud.offline-requests.import') }}" enctype="multipart/form-data">@csrf<h3>Import and issue</h3><div class="form-grid"><label class="field field--full">Activation request (.tpr)<input type="file" name="activation_request" accept=".tpr,.json,application/json" required><small>Maximum 64 KB. TablePlay verifies the request signature, device identity and age.</small></label><label class="field field--full">Restaurant subscription<select name="subscription_id" required><option value="">Select the customer and plan</option>@foreach($offlineSubscriptions as $subscription)<option value="{{ $subscription->id }}" @selected((string)old('subscription_id')===(string)$subscription->id)>{{ $subscription->restaurant->name }} &middot; {{ $subscription->plan->name }} &middot; {{ ucfirst($subscription->status) }}</option>@endforeach</select></label></div><button class="button button--accent button--block" type="submit" @disabled(!$signingReady)>Verify request and issue licence</button>@unless($signingReady)<p class="modal-note">Configure the Cloud Ed25519 signing keypair before issuing an offline licence.</p>@endunless</form><div><h3>Secure offline workflow</h3><div class="timeline"><article><i></i><div><strong>1. Restaurant exports a request</strong><small>The .tpr contains only server identity and a self-signed challenge.</small></div></article><article><i></i><div><strong>2. Super Admin verifies and issues</strong><small>The subscription, installation limit and computer binding are checked here. Offline access must be refreshed within {{ max(1, (int) config('tableplay.offline_license_lease_days', 30)) }} days.</small></div></article><article><i></i><div><strong>3. Restaurant imports the licence</strong><small>Return the stored .tpl file by USB. No internet connection is required.</small></div></article></div></div></div></div></section>

@if($offlineRequests->isNotEmpty())<section class="card" style="margin-bottom:18px"><div class="card__header"><div><h2>Offline request history</h2><p>Issued files are stored exactly as signed and can be downloaded again without changing their revision.</p></div><span class="status-badge status-badge--{{ $offlineRequests->where('status','issued')->count() ? 'success' : 'warning' }}"><i></i>{{ $offlineRequests->count() }} recent</span></div><div class="table-wrap"><table class="data-table data-table--responsive"><thead><tr><th>Restaurant server</th><th>Request</th><th>Subscription</th><th>Status</th><th>Imported</th><th>Licence</th></tr></thead><tbody>@foreach($offlineRequests as $offlineRequest)<tr @if((int)session('issued_offline_request_id')===$offlineRequest->id) style="background:var(--success-soft)" @endif><td><span class="table-primary"><strong>{{ $offlineRequest->device_name }}</strong><small>{{ $offlineRequest->server_version }} &middot; {{ str($offlineRequest->installation_uuid)->limit(20) }}</small></span></td><td data-label="Request"><span class="table-primary"><strong>{{ str($offlineRequest->request_id)->limit(18) }}</strong><small>Expires {{ $offlineRequest->expires_at->format('d M Y H:i') }}</small></span></td><td data-label="Subscription">{{ $offlineRequest->subscription?->restaurant?->name ?? 'Not assigned' }}@if($offlineRequest->subscription)<br><small>{{ $offlineRequest->subscription->plan->name }}</small>@endif</td><td data-label="Status"><x-status :value="$offlineRequest->status" /></td><td data-label="Imported">{{ $offlineRequest->imported_at->diffForHumans() }}<br><small>{{ $offlineRequest->issuer?->name }}</small></td><td data-label="Licence">@if($offlineRequest->status==='issued')<a class="button button--small" href="{{ route('superadmin.cloud.offline-requests.license',$offlineRequest) }}"><x-icon name="download" size="15" /> Download r{{ $offlineRequest->license_revision }}</a>@else<span class="muted">Not issued</span>@endif</td></tr>@endforeach</tbody></table></div></section>@endif

<div class="stats-grid cloud-metrics"><article class="stat-card"><span>Customers</span><strong class="stat-card__value">{{ $metrics['customers'] }}</strong><small class="stat-card__meta">{{ $metrics['active'] }} active accounts</small></article><article class="stat-card"><span>Monthly recurring</span><strong class="stat-card__value">{{ $commercialSettings->currency }} {{ number_format($metrics['mrr'], 0) }}</strong><small class="stat-card__meta">Based on active plans</small></article><article class="stat-card"><span>Recorded revenue</span><strong class="stat-card__value">{{ $commercialSettings->currency }} {{ number_format($metrics['revenue'], 0) }}</strong><small class="stat-card__meta">Completed payments</small></article><article class="stat-card"><span>Outstanding</span><strong class="stat-card__value">{{ $commercialSettings->currency }} {{ number_format($metrics['outstanding'], 0) }}</strong><small class="stat-card__meta">{{ $metrics['renewals_due'] }} renewals in 30 days</small></article></div>

<section class="card cloud-filter"><form class="card__body inline-form" method="get"><label class="field">Search<input name="q" value="{{ request('q') }}" placeholder="Restaurant, owner or email"></label><label class="field">Account<select name="status"><option value="">All accounts</option>@foreach(['active','suspended','closed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label class="field">Plan<select name="plan_id"><option value="">All plans</option>@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected((string)request('plan_id')===(string)$plan->id)>{{ $plan->name }}</option>@endforeach</select></label><label class="field">Subscription<select name="subscription_status"><option value="">All states</option>@foreach(['trial','active','grace','suspended','expired'] as $status)<option value="{{ $status }}" @selected(request('subscription_status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label class="field">Renewal<select name="renewal_days"><option value="">Any date</option><option value="7" @selected(request('renewal_days')==='7')>Next 7 days</option><option value="30" @selected(request('renewal_days')==='30')>Next 30 days</option></select></label><label class="field">Health<select name="health"><option value="">All health</option><option value="attention" @selected(request('health')==='attention')>Needs attention</option></select></label><button class="button" type="submit">Filter</button><a class="button button--secondary" href="{{ route('superadmin.cloud.index') }}">Reset</a></form></section>

@if($reminders->isNotEmpty())<section class="card renewal-reminders"><div class="card__header"><div><h2>Renewal reminders</h2><p>Created automatically at 30, 14, 7 and 1 day before expiry</p></div><span class="status-badge status-badge--warning"><i></i>{{ $reminders->count() }} recent</span></div><div class="card__body"><div class="feature-list">@foreach($reminders as $reminder)<span class="feature-pill">{{ $reminder->subscription->restaurant->name }} · {{ $reminder->days_before_expiry }} days</span>@endforeach</div></div></section>@endif

<div class="customer-grid">
@forelse($restaurants as $restaurant)
@php($subscription = $restaurant->subscriptions->first())
<article class="customer-card">
    <header><div class="customer-identity"><span>{{ strtoupper(substr($restaurant->name,0,2)) }}</span><div><h3>{{ $restaurant->name }}</h3><small>{{ $restaurant->owner_name ?: 'Owner not recorded' }} · {{ $restaurant->owner_email ?: 'No email' }}</small></div></div><x-status :value="$restaurant->status" /></header>
    <div class="customer-plan"><div><small>Current plan</small><strong>{{ $subscription?->plan?->name ?? 'No subscription' }}</strong></div><div><small>Renewal</small><strong>{{ $subscription?->expires_at?->format('d M Y') ?? 'No expiry' }}</strong></div><div><small>Installations</small><strong>{{ $subscription?->installations->where('status','active')->count() ?? 0 }} / {{ $subscription?->max_installations ?? 0 }}</strong></div></div>
    <div class="customer-finance"><span>{{ $restaurant->invoices->count() }} invoices</span><span>INR {{ number_format($restaurant->payments->sum('amount'),0) }} received</span></div>
    <footer><button class="button button--secondary button--small" type="button" data-dialog-open="customer-{{ $restaurant->id }}">Manage customer</button>@if($subscription)<form method="post" action="{{ route('superadmin.cloud.keys.issue',$subscription) }}">@csrf<button class="button button--small" type="submit">New activation key</button></form>@endif</footer>
</article>
@empty<div class="empty-state cloud-empty"><span class="empty-state__icon"><x-icon name="team" size="26" /></span><strong>{{ request()->hasAny(['q','status','plan_id','subscription_status','renewal_days','health']) ? 'No customers match these filters' : 'Add your first restaurant customer' }}</strong><p>{{ request()->hasAny(['q','status','plan_id','subscription_status','renewal_days','health']) ? 'Try resetting one or more filters to expand the results.' : 'Create a customer, choose a plan and issue the first secure activation key.' }}</p>@if(request()->hasAny(['q','status','plan_id','subscription_status','renewal_days','health']))<a class="button button--secondary button--small" href="{{ route('superadmin.cloud.index') }}">Clear all filters</a>@else<button class="button button--accent button--small" type="button" data-dialog-open="new-customer"><x-icon name="plus" size="15" /> Add first customer</button>@endif</div>@endforelse
</div>

<dialog class="modal-dialog" id="new-customer"><div class="modal-dialog__surface"><div class="modal-dialog__header"><div><span class="superadmin-kicker">Onboarding</span><h2>Add restaurant customer</h2></div><button class="icon-button" type="button" data-dialog-close><x-icon name="close" /></button></div><form method="post" action="{{ route('superadmin.cloud.restaurants.store') }}">@csrf<div class="modal-dialog__body"><div class="form-grid"><label class="field field--full">Restaurant name<input name="name" required></label><label class="field">Owner name<input name="owner_name"></label><label class="field">Owner email<input type="email" name="owner_email"></label><label class="field">Owner phone<input name="owner_phone"></label><label class="field">Initial plan<select name="commercial_plan_id" required>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select></label><label class="field">Duration days<input type="number" name="duration_days" min="1" max="3650" value="365"></label></div><div class="form-actions"><button class="button button--secondary" type="button" data-dialog-close>Cancel</button><button class="button button--accent" type="submit">Create customer and key</button></div></div></form></div></dialog>

<dialog class="modal-dialog" id="commercial-settings"><div class="modal-dialog__surface"><div class="modal-dialog__header"><div><span class="superadmin-kicker">Billing identity</span><h2>Commercial invoice settings</h2></div><button class="icon-button" type="button" data-dialog-close><x-icon name="close" /></button></div><form method="post" action="{{ route('superadmin.cloud.settings.update') }}">@csrf @method('PUT')<div class="modal-dialog__body"><div class="form-grid"><label class="field field--full">Legal business name<input name="legal_name" value="{{ $commercialSettings->legal_name }}" required></label><label class="field">Tax/GST number<input name="tax_number" value="{{ $commercialSettings->tax_number }}"></label><label class="field">Currency<input name="currency" value="{{ $commercialSettings->currency }}" maxlength="8" required></label><label class="field">Invoice prefix<input name="invoice_prefix" value="{{ $commercialSettings->invoice_prefix }}" maxlength="20" required></label><label class="field field--full">Registered billing address<textarea name="billing_address">{{ $commercialSettings->billing_address }}</textarea></label></div><div class="form-actions"><button class="button button--secondary" type="button" data-dialog-close>Cancel</button><button class="button" type="submit">Save settings</button></div></div></form></div></dialog>

@foreach($restaurants as $restaurant)
@php($subscription = $restaurant->subscriptions->first())
<dialog class="modal-dialog modal-dialog--wide" id="customer-{{ $restaurant->id }}"><div class="modal-dialog__surface"><div class="modal-dialog__header"><div><span class="superadmin-kicker">Customer account</span><h2>{{ $restaurant->name }}</h2></div><button class="icon-button" type="button" data-dialog-close><x-icon name="close" /></button></div><div class="modal-dialog__body customer-manager">
    <details open><summary>Customer profile</summary><form method="post" action="{{ route('superadmin.cloud.restaurants.update',$restaurant) }}">@csrf @method('PUT')<div class="form-grid"><label class="field">Restaurant name<input name="name" value="{{ $restaurant->name }}" required></label><label class="field">Owner name<input name="owner_name" value="{{ $restaurant->owner_name }}"></label><label class="field">Owner email<input type="email" name="owner_email" value="{{ $restaurant->owner_email }}"></label><label class="field">Owner phone<input name="owner_phone" value="{{ $restaurant->owner_phone }}"></label><label class="field">Billing name<input name="billing_name" value="{{ $restaurant->billing_name }}"></label><label class="field">Billing email<input type="email" name="billing_email" value="{{ $restaurant->billing_email }}"></label><label class="field">Tax/GST number<input name="tax_number" value="{{ $restaurant->tax_number }}"></label><label class="field field--full">Billing address<textarea name="billing_address">{{ $restaurant->billing_address }}</textarea></label><label class="field field--full">Internal support notes<textarea name="notes">{{ $restaurant->notes }}</textarea></label></div><div class="form-actions"><button class="button" type="submit">Save customer</button></div></form><form method="post" action="{{ route('superadmin.cloud.restaurants.status',$restaurant) }}" class="inline-form customer-status">@csrf<label class="field">Account status<select name="status">@foreach(['active','suspended','closed'] as $status)<option value="{{ $status }}" @selected($restaurant->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><button class="button button--secondary" type="submit" data-confirm="Change this customer account status?" data-confirm-detail="The action will be recorded in the platform audit log.">Update status</button></form></details>
    @if($subscription)<details open><summary>Subscription lifecycle</summary><div class="subscription-summary"><strong>{{ $subscription->plan->name }}</strong><x-status :value="$subscription->status" /><span>{{ $subscription->expires_at?->format('d M Y') ?? 'No expiry' }}</span></div><form class="form-grid form-grid--3" method="post" action="{{ route('superadmin.cloud.subscriptions.renew',$subscription) }}">@csrf<label class="field">Renew or change plan<select name="commercial_plan_id">@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected($plan->id===$subscription->commercial_plan_id)>{{ $plan->name }}</option>@endforeach</select></label><label class="field">Duration days<input type="number" name="duration_days" value="365" min="1" max="3650"></label><label class="field">Reason<input name="reason" placeholder="Renewal, upgrade or extension"></label><button class="button field--full" type="submit">Apply plan and renewal</button></form><form class="inline-form lifecycle-status" method="post" action="{{ route('superadmin.cloud.subscriptions.status',$subscription) }}">@csrf<label class="field">Change status<select name="status">@foreach(['trial','active','grace','suspended','expired'] as $status)<option value="{{ $status }}" @selected($subscription->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label class="field">Required reason<input name="reason" required></label><button class="button button--secondary" type="submit" data-confirm="Apply this subscription status?" data-confirm-detail="A permanent lifecycle event will be recorded.">Apply status</button></form><div class="timeline">@forelse($subscription->events->take(8) as $event)<article><i></i><div><strong>{{ str($event->event)->replace('_',' ')->title() }}</strong><small>{{ $event->effective_at->format('d M Y H:i') }} · {{ $event->reason ?: 'System operation' }}</small></div></article>@empty<p class="muted">No lifecycle events recorded yet.</p>@endforelse</div></details>@endif
    <details open><summary>Invoices and payments</summary><div class="billing-split"><form method="post" action="{{ route('superadmin.cloud.invoices.store',$restaurant) }}">@csrf<h3>Create invoice</h3><input type="hidden" name="cloud_subscription_id" value="{{ $subscription?->id }}"><div class="form-grid"><label class="field">Subtotal<input type="number" name="subtotal" min="0.01" step="0.01" required></label><label class="field">Tax rate %<input type="number" name="tax_rate" min="0" max="100" step="0.001" value="18"></label><label class="field">Currency<input name="currency" value="INR" maxlength="8" required></label><label class="field">Due date<input type="date" name="due_on" min="{{ today()->format('Y-m-d') }}"></label><label class="field field--full">Notes<input name="notes"></label></div><button class="button button--accent button--block" type="submit">Create invoice</button></form><form method="post" action="{{ route('superadmin.cloud.payments.store',$restaurant) }}">@csrf<h3>Record payment</h3><div class="form-grid"><label class="field field--full">Invoice<select name="cloud_invoice_id"><option value="">Unallocated payment</option>@foreach($restaurant->invoices->whereNotIn('status',['paid','void']) as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->invoice_number }} · {{ $invoice->currency }} {{ $invoice->total }}</option>@endforeach</select></label><label class="field">Amount<input type="number" name="amount" min="0.01" step="0.01" required></label><label class="field">Method<select name="method">@foreach(['upi','bank','card','cash','other'] as $method)<option value="{{ $method }}">{{ strtoupper($method) }}</option>@endforeach</select></label><label class="field">Paid at<input type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label class="field">Reference<input name="reference"></label></div><button class="button button--block" type="submit">Record payment</button></form></div><div class="table-wrap invoice-list"><table class="data-table"><thead><tr><th>Invoice</th><th>Total</th><th>Status</th><th>Due</th></tr></thead><tbody>@forelse($restaurant->invoices as $invoice)<tr><td><a href="{{ route('superadmin.cloud.invoices.show',$invoice) }}" target="_blank">{{ $invoice->invoice_number }}</a></td><td>{{ $invoice->currency }} {{ number_format($invoice->total,2) }}</td><td><x-status :value="$invoice->status" /></td><td>{{ $invoice->due_on?->format('d M Y') ?? 'On issue' }}</td></tr>@empty<tr><td colspan="4">No invoices yet.</td></tr>@endforelse</tbody></table></div></details>
</div></div></dialog>
@endforeach
@if($restaurants->isNotEmpty())<section class="card commercial-control-panel"><div class="card__header"><div><h2>Scheduled changes and financial controls</h2><p>Future plan changes, invoice voids and refunds require an auditable reason.</p></div></div><div class="card__body">
@foreach($restaurants as $restaurant)@php($subscription=$restaurant->subscriptions->first())@if($subscription)<details><summary>{{ $restaurant->name }} · {{ $subscription->plan->name }}</summary><div class="commercial-control-grid"><form method="post" action="{{ route('superadmin.cloud.subscriptions.schedule',$subscription) }}">@csrf<h3>Schedule plan change</h3><div class="form-grid"><label class="field">New plan<select name="commercial_plan_id">@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select></label><label class="field">Effective date<input type="datetime-local" name="scheduled_change_at" min="{{ now()->addMinute()->format('Y-m-d\TH:i') }}" required></label><label class="field">Duration days<input type="number" name="duration_days" min="1" max="3650" placeholder="No expiry"></label><label class="field">Reason<input name="reason" required></label></div><button class="button button--small" type="submit">Schedule change</button>@if($subscription->scheduledPlan)<p class="modal-note">Scheduled: {{ $subscription->scheduledPlan->name }} on {{ $subscription->scheduled_change_at->format('d M Y H:i') }}</p>@endif</form><div><h3>Invoices and payments</h3>@foreach($restaurant->invoices->take(5) as $invoice)<div class="financial-action"><span><strong>{{ $invoice->invoice_number }}</strong><small>{{ $invoice->status }} · {{ $invoice->currency }} {{ $invoice->total }}</small></span>@if(!in_array($invoice->status,['paid','void']))<form method="post" action="{{ route('superadmin.cloud.invoices.void',$invoice) }}">@csrf<input name="reason" placeholder="Void reason" required><button class="button button--small button--danger" type="submit" data-confirm="Void this invoice?" data-confirm-detail="This action is permanent and audited." data-confirm-tone="danger">Void</button></form>@endif</div>@endforeach @foreach($restaurant->payments->where('status','completed')->take(5) as $payment)<div class="financial-action"><span><strong>{{ $payment->payment_number }}</strong><small>{{ strtoupper($payment->method) }} · INR {{ $payment->amount }}</small></span><form method="post" action="{{ route('superadmin.cloud.payments.refund',$payment) }}">@csrf<input name="reason" placeholder="Refund reason" required><button class="button button--small button--warning" type="submit" data-confirm="Record this payment as refunded?" data-confirm-detail="The invoice balance and audit trail will be updated.">Refund</button></form></div>@endforeach</div></div></details>@endif @endforeach
</div></section>@endif
@endsection
