@extends('layouts.app')
@section('title', 'Super Admin Command Center')
@section('eyebrow', 'TablePlay Super Admin')
@section('page-title', 'Platform Command Center')
@section('content')
<section class="superadmin-hero"><div><span class="superadmin-kicker"><x-icon name="license" size="15" /> Commercial operations</span><h2>Plans, licenses and growth in one place.</h2><p>Create offers, control availability, activate restaurant licenses and protect every subscription record.</p></div><div class="page-heading__actions"><button class="button button--accent" type="button" data-dialog-open="create-plan-dialog"><x-icon name="plus" size="17" /> New plan</button><a class="button button--secondary" href="{{ route('superadmin.cloud.index') }}"><x-icon name="team" size="16" /> Restaurant customers</a></div></section>

<div class="stats-grid superadmin-stats">
    <article class="stat-card"><span class="stat-card__icon"><x-icon name="license" size="18" /></span><span class="stat-card__label">Current plan</span><strong class="stat-card__value">{{ data_get($entitlements, 'plan.name', 'Not licensed') }}</strong><small class="stat-card__meta">{{ $entitlements['license_reference'] ?? 'No active license' }}</small></article>
    <article class="stat-card"><span class="stat-card__icon"><x-icon name="health" size="18" /></span><span class="stat-card__label">License status</span><strong class="stat-card__value">{{ ucfirst($entitlements['status']) }}</strong><small class="stat-card__meta">Server-verified access</small></article>
    <article class="stat-card"><span class="stat-card__icon"><x-icon name="report" size="18" /></span><span class="stat-card__label">Published plans</span><strong class="stat-card__value">{{ $platformStats['active_plans'] }}</strong><small class="stat-card__meta">{{ $plans->count() }} total offers</small></article>
    <article class="stat-card"><span class="stat-card__icon"><x-icon name="team" size="18" /></span><span class="stat-card__label">License records</span><strong class="stat-card__value">{{ $platformStats['activations'] }}</strong><small class="stat-card__meta">{{ $platformStats['cloud_restaurants'] }} restaurant customers</small></article>
</div>

<div class="content-grid content-grid--2 superadmin-overview">
    <section class="card"><div class="card__header"><div><h2>Current restaurant access</h2><p>Live entitlements enforced by the server</p></div><span class="status-badge status-badge--{{ $entitlements['licensed'] ? 'active' : 'disabled' }}"><i></i>{{ $entitlements['licensed'] ? 'Licensed' : 'Restricted' }}</span></div><div class="card__body">
        <div class="entitlement-meter"><div><span>Paired customer tablets</span><strong>{{ data_get($entitlements, 'usage.paired_tables', 0) }} / {{ data_get($entitlements, 'limits.paired_tables') ?? 'Unlimited' }}</strong></div><div class="entitlement-meter__track"><i style="width:{{ data_get($entitlements, 'limits.paired_tables') ? min(100, data_get($entitlements, 'usage.paired_tables', 0) / max(1, data_get($entitlements, 'limits.paired_tables')) * 100) : 100 }}%"></i></div></div>
        <div class="feature-list feature-list--compact">@forelse(collect($entitlements['features'] ?? [])->filter() as $feature => $enabled)<span class="feature-pill"><x-icon name="check" size="13" /> {{ $featureCatalog[$feature] ?? str($feature)->replace('_', ' ')->title() }}</span>@empty<span class="muted">No product features are enabled.</span>@endforelse</div>
        @if($currentSubscription)<div class="subscription-actions"><span>Started {{ $currentSubscription->starts_at?->format('d M Y') }} · {{ $currentSubscription->expires_at?->format('d M Y') ?? 'No expiry' }}</span>@if($currentSubscription->status === 'suspended')<form method="post" action="{{ route('superadmin.resume', $currentSubscription) }}">@csrf<button class="button button--small" type="submit">Resume access</button></form>@else<form method="post" action="{{ route('superadmin.suspend', $currentSubscription) }}">@csrf<button class="button button--small button--warning" type="submit" data-confirm="Suspend the current subscription?" data-confirm-detail="Licensed features will be restricted until it is resumed.">Suspend access</button></form>@endif</div>@endif
    </div></section>
    <section class="card"><div class="card__header"><div><h2>Activate a plan</h2><p>Change packages without reinstalling apps</p></div><x-icon name="refresh" /></div><div class="card__body"><form method="post" action="{{ route('superadmin.activate') }}" class="form-grid">@csrf<label class="field field--full">Published plan<select name="plan_id" required>@forelse($activePlans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }} — {{ $plan->max_paired_tables === null ? 'Unlimited tablets' : $plan->max_paired_tables.' tablets' }}</option>@empty<option disabled>No active plans available</option>@endforelse</select></label><label class="field">Duration (days)<input type="number" name="duration_days" min="1" max="3650" placeholder="No expiry"></label><div class="activation-note"><x-icon name="health" size="18" /><span>A signed license applies features immediately.</span></div><button class="button button--accent field--full" type="submit" @disabled($activePlans->isEmpty())>Activate selected plan</button></form></div></section>
</div>

<section class="section-heading"><div><span class="superadmin-kicker">Product catalog</span><h2>Commercial plans</h2><p>Edit pricing, table limits, features and sales availability.</p></div><button class="button button--secondary" type="button" data-dialog-open="create-plan-dialog"><x-icon name="plus" size="16" /> Create plan</button></section>
<div class="plan-grid">
@forelse($plans as $plan)
<article class="plan-card {{ $plan->is_featured ? 'plan-card--featured' : '' }} {{ ! $plan->is_active ? 'plan-card--archived' : '' }}">@if($plan->is_featured)<span class="plan-card__ribbon">Recommended</span>@endif<header><div><span class="status-badge status-badge--{{ $plan->is_active ? 'active' : 'disabled' }}"><i></i>{{ $plan->is_active ? 'Published' : 'Archived' }}</span><h3>{{ $plan->name }}</h3><small>{{ $plan->slug }}</small></div><button class="plan-edit" type="button" data-dialog-open="edit-plan-{{ $plan->id }}" aria-label="Edit {{ $plan->name }}"><x-icon name="settings" size="17" /></button></header><p class="plan-card__description">{{ $plan->description ?: 'A flexible TablePlay package ready for your commercial offer.' }}</p><div class="plan-price"><strong>{{ $plan->monthly_price !== null ? 'INR '.number_format((float)$plan->monthly_price, 0) : 'Custom' }}</strong><span>{{ $plan->monthly_price !== null ? '/ month' : 'pricing' }}</span></div>@if($plan->annual_price !== null)<small class="plan-annual">INR {{ number_format((float)$plan->annual_price, 0) }} billed annually</small>@endif<div class="plan-limit"><x-icon name="device" size="18" /><span><strong>{{ $plan->max_paired_tables ?? 'Unlimited' }}</strong> paired table tablets</span></div><div class="feature-list">@foreach(collect($plan->features)->filter() as $feature => $enabled)<span class="feature-pill"><x-icon name="check" size="12" /> {{ $featureCatalog[$feature] ?? str($feature)->replace('_', ' ')->title() }}</span>@endforeach</div><footer><span>{{ $plan->usage_count }} license {{ Str::plural('record', $plan->usage_count) }}</span><div class="plan-actions"><form method="post" action="{{ route('superadmin.plans.toggle', $plan) }}">@csrf<button class="button button--small button--secondary" type="submit" data-confirm="{{ $plan->is_active ? 'Archive' : 'Restore' }} {{ $plan->name }}?" data-confirm-detail="Subscription history remains protected.">{{ $plan->is_active ? 'Archive' : 'Restore' }}</button></form>@if($plan->usage_count === 0)<form method="post" action="{{ route('superadmin.plans.destroy', $plan) }}">@csrf @method('DELETE')<button class="button button--small button--danger" type="submit" data-confirm="Permanently delete {{ $plan->name }}?" data-confirm-detail="This unused plan cannot be recovered." data-confirm-tone="danger">Delete</button></form>@endif</div></footer></article>
@empty<div class="empty-state"><h3>No plans yet</h3><p>Create the first commercial offer.</p></div>@endforelse
</div>

<section class="card"><div class="card__header"><div><h2>License activity</h2><p>Complete activation and status history</p></div><span class="status-badge"><i></i>{{ $subscriptions->count() }} recent</span></div><div class="table-wrap"><table class="data-table data-table--responsive"><thead><tr><th>License</th><th>Plan</th><th>Status</th><th>Source</th><th>Started</th><th>Expires</th></tr></thead><tbody>@forelse($subscriptions as $subscription)<tr><td data-label="License"><div class="table-primary"><strong>{{ $subscription->license_reference }}</strong><small>{{ Str::limit($subscription->installation_uuid, 22) }}</small></div></td><td data-label="Plan">{{ $subscription->plan?->name ?? 'Removed plan' }}</td><td data-label="Status"><span class="status-badge status-badge--{{ in_array($subscription->status, ['active','trial']) ? 'active' : ($subscription->status === 'suspended' ? 'disabled' : 'warning') }}"><i></i>{{ $subscription->status }}</span></td><td data-label="Source">{{ ucfirst($subscription->source ?? 'local') }}</td><td data-label="Started">{{ $subscription->starts_at?->format('d M Y') }}</td><td data-label="Expires">{{ $subscription->expires_at?->format('d M Y') ?? 'No expiry' }}</td></tr>@empty<tr><td colspan="6">No license activity recorded.</td></tr>@endforelse</tbody></table></div></section>

<dialog class="modal-dialog" id="create-plan-dialog"><div class="modal-dialog__surface"><div class="modal-dialog__header"><div><span class="superadmin-kicker">New offer</span><h2>Create commercial plan</h2></div><button class="icon-button" type="button" data-dialog-close aria-label="Close"><x-icon name="close" /></button></div><form method="post" action="{{ route('superadmin.plans.store') }}">@csrf<div class="modal-dialog__body">@include('superadmin._plan-form', ['plan' => null])<div class="form-actions"><button class="button button--secondary" type="button" data-dialog-close>Cancel</button><button class="button button--accent" type="submit">Create plan</button></div></div></form></div></dialog>
@foreach($plans as $plan)<dialog class="modal-dialog" id="edit-plan-{{ $plan->id }}"><div class="modal-dialog__surface"><div class="modal-dialog__header"><div><span class="superadmin-kicker">Plan settings</span><h2>Edit {{ $plan->name }}</h2></div><button class="icon-button" type="button" data-dialog-close aria-label="Close"><x-icon name="close" /></button></div><form method="post" action="{{ route('superadmin.plans.update', $plan) }}">@csrf @method('PUT')<div class="modal-dialog__body">@include('superadmin._plan-form', ['plan' => $plan])<div class="form-actions"><button class="button button--secondary" type="button" data-dialog-close>Cancel</button><button class="button button--accent" type="submit">Save changes</button></div></div></form></div></dialog>@endforeach
@endsection
