@extends('layouts.app')
@section('title','Super Admin') @section('eyebrow','TablePlay platform') @section('page-title','Licensing & plans')
@section('content')
<div class="page-heading"><div><h2>Commercial control center</h2><p>Manage this installation's plan, entitlements and renewal history.</p></div><div class="page-heading__actions"><a class="button" href="{{ route('superadmin.cloud.index') }}">Open TablePlay Cloud</a></div></div>
<div class="content-grid content-grid--2"><section class="card"><div class="card__header"><div><h2>Current entitlement</h2><p>Server-enforced status</p></div></div><div class="card__body"><div class="stats-grid"><article class="stat-card"><span>Plan</span><strong>{{ data_get($entitlements,'plan.name','Missing') }}</strong></article><article class="stat-card"><span>Status</span><strong>{{ ucfirst($entitlements['status']) }}</strong></article><article class="stat-card"><span>Paired tablets</span><strong>{{ data_get($entitlements,'usage.paired_tables',0) }} / {{ data_get($entitlements,'limits.paired_tables') ?? 'Unlimited' }}</strong></article></div><p><strong>License:</strong> {{ $entitlements['license_reference'] ?? 'Not activated' }}</p></div></section>
<section class="card"><div class="card__header"><div><h2>Activate plan</h2><p>Updates features without reinstalling apps</p></div></div><div class="card__body"><form method="post" action="{{ route('superadmin.activate') }}" class="form-grid">@csrf<label class="field">Plan<select name="plan_id" required>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }} — {{ $plan->max_paired_tables===null?'Unlimited':$plan->max_paired_tables.' tablets' }}</option>@endforeach</select></label><label class="field">Duration days (optional)<input type="number" name="duration_days" min="1" max="3650"></label><button class="button button--accent" type="submit">Activate plan</button></form></div></section></div>
<section class="card"><div class="card__header"><div><h2>Plans</h2><p>Features and limits enforced by Laravel</p></div></div><div class="card__body"><div class="table-wrap"><table><thead><tr><th>Plan</th><th>Table tablets</th><th>Features</th></tr></thead><tbody>@foreach($plans as $plan)<tr><td><strong>{{ $plan->name }}</strong></td><td>{{ $plan->max_paired_tables===null?'Unlimited':$plan->max_paired_tables }}</td><td>{{ collect($plan->features)->filter()->keys()->map(fn($v)=>str($v)->replace('_',' ')->title())->join(', ') }}</td></tr>@endforeach</tbody></table></div></div></section>
<section class="card"><div class="card__header"><div><h2>License history</h2><p>Activation and renewal trail</p></div></div><div class="card__body"><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Plan</th><th>Status</th><th>Started</th><th>Expires</th></tr></thead><tbody>@foreach($subscriptions as $subscription)<tr><td>{{ $subscription->license_reference }}</td><td>{{ $subscription->plan->name }}</td><td>{{ ucfirst($subscription->status) }}</td><td>{{ $subscription->starts_at?->format('d M Y') }}</td><td>{{ $subscription->expires_at?->format('d M Y') ?? 'No expiry' }}</td></tr>@endforeach</tbody></table></div></div></section>
@endsection
