<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('dining_tables', function (Blueprint $t) { $t->id(); $t->string('table_code')->unique(); $t->string('table_name'); $t->unsignedSmallInteger('capacity')->default(4); $t->enum('status',['available','occupied','reserved','cleaning','disabled'])->default('available'); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('devices', function (Blueprint $t) { $t->id(); $t->uuid('device_uuid')->unique(); $t->string('device_name'); $t->enum('device_type',['tablet','counter','kitchen']); $t->ipAddress('ip_address')->nullable(); $t->string('auth_token_hash')->nullable(); $t->timestamp('last_seen_at')->nullable(); $t->string('app_version')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); $t->index(['last_seen_at','is_active']); });
        Schema::create('device_pairings', function (Blueprint $t) { $t->id(); $t->foreignId('device_id')->constrained()->cascadeOnDelete(); $t->foreignId('dining_table_id')->constrained()->cascadeOnDelete(); $t->foreignId('paired_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('paired_at'); $t->timestamp('unpaired_at')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); $t->index(['device_id','is_active']); $t->index(['dining_table_id','is_active']); });
        Schema::create('categories', function (Blueprint $t) { $t->id(); $t->string('name'); $t->text('description')->nullable(); $t->string('image_path')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('menu_items', function (Blueprint $t) { $t->id(); $t->foreignId('category_id')->constrained()->restrictOnDelete(); $t->string('name'); $t->text('description')->nullable(); $t->string('image_path')->nullable(); $t->decimal('price',12,2); $t->enum('food_type',['veg','non_veg','egg','other'])->default('other'); $t->unsignedSmallInteger('preparation_minutes')->nullable(); $t->boolean('is_available')->default(true); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('table_sessions', function (Blueprint $t) { $t->id(); $t->string('session_code')->unique(); $t->foreignId('dining_table_id')->constrained()->restrictOnDelete(); $t->unsignedSmallInteger('guest_count')->default(1); $t->foreignId('opened_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('opened_at'); $t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('closed_at')->nullable(); $t->enum('status',['open','billing','closed','cancelled'])->default('open'); $t->timestamps(); $t->index(['dining_table_id','status']); });
        Schema::create('orders', function (Blueprint $t) { $t->id(); $t->string('order_number')->unique(); $t->foreignId('table_session_id')->constrained()->restrictOnDelete(); $t->unsignedInteger('order_sequence'); $t->enum('status',['pending','confirmed','preparing','ready','served','cancelled','rejected'])->default('pending'); $t->decimal('subtotal',12,2); $t->decimal('tax_amount',12,2)->default(0); $t->decimal('discount_amount',12,2)->default(0); $t->decimal('total_amount',12,2); $t->text('customer_note')->nullable(); $t->foreignId('confirmed_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('confirmed_at')->nullable(); $t->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete(); $t->text('cancel_reason')->nullable(); $t->timestamps(); $t->index(['table_session_id','status','created_at']); });
        Schema::create('order_items', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->foreignId('menu_item_id')->constrained()->restrictOnDelete(); $t->string('item_name_snapshot'); $t->decimal('unit_price',12,2); $t->unsignedInteger('quantity'); $t->decimal('line_total',12,2); $t->text('special_instruction')->nullable(); $t->enum('status',['pending','preparing','ready','served','cancelled'])->default('pending'); $t->timestamps(); $t->index(['order_id','status']); });
        Schema::create('order_status_logs', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->string('from_status')->nullable(); $t->string('to_status'); $t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete(); $t->text('note')->nullable(); $t->timestamp('created_at')->useCurrent(); });
        Schema::create('service_requests', function (Blueprint $t) { $t->id(); $t->foreignId('table_session_id')->constrained()->cascadeOnDelete(); $t->enum('request_type',['call_waiter','water','bill','other']); $t->text('message')->nullable(); $t->enum('status',['pending','acknowledged','completed','cancelled'])->default('pending'); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->index(['status','created_at']); });
        Schema::create('bills', function (Blueprint $t) { $t->id(); $t->string('bill_number')->unique(); $t->foreignId('table_session_id')->unique()->constrained()->restrictOnDelete(); $t->decimal('subtotal',12,2); $t->decimal('tax_amount',12,2); $t->decimal('discount_amount',12,2)->default(0); $t->decimal('grand_total',12,2); $t->enum('payment_status',['unpaid','paid','void'])->default('unpaid'); $t->foreignId('generated_by')->constrained('users')->restrictOnDelete(); $t->timestamp('generated_at'); $t->timestamp('paid_at')->nullable(); $t->timestamps(); });
        Schema::create('payments', function (Blueprint $t) { $t->id(); $t->foreignId('bill_id')->constrained()->restrictOnDelete(); $t->string('payment_number')->unique(); $t->enum('method',['cash'])->default('cash'); $t->decimal('amount',12,2); $t->decimal('received_amount',12,2); $t->decimal('change_amount',12,2); $t->foreignId('received_by')->constrained('users')->restrictOnDelete(); $t->timestamp('paid_at'); $t->text('note')->nullable(); $t->timestamps(); });
        Schema::create('games', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->enum('player_mode',['one','two','four'])->default('one'); $t->string('game_path'); $t->string('thumbnail_path')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('game_sessions', function (Blueprint $t) { $t->id(); $t->foreignId('table_session_id')->constrained()->cascadeOnDelete(); $t->foreignId('trigger_order_id')->constrained('orders')->restrictOnDelete(); $t->dateTime('started_at'); $t->dateTime('expires_at'); $t->dateTime('stopped_at')->nullable(); $t->foreignId('stopped_by')->nullable()->constrained('users')->nullOnDelete(); $t->enum('status',['active','expired','stopped'])->default('active'); $t->timestamps(); $t->index(['table_session_id','status','expires_at']); });
        Schema::create('game_results', function (Blueprint $t) { $t->id(); $t->foreignId('game_session_id')->constrained()->cascadeOnDelete(); $t->foreignId('game_id')->constrained()->restrictOnDelete(); $t->string('player_name')->nullable(); $t->unsignedSmallInteger('player_position')->nullable(); $t->bigInteger('score')->default(0); $t->unsignedInteger('duration_seconds')->nullable(); $t->dateTime('played_at'); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('device_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->string('entity_type')->nullable(); $t->unsignedBigInteger('entity_id')->nullable(); $t->json('old_values')->nullable(); $t->json('new_values')->nullable(); $t->ipAddress('ip_address')->nullable(); $t->timestamp('created_at')->useCurrent(); });
    }
    public function down(): void
    {
        foreach (['audit_logs','game_results','game_sessions','games','payments','bills','service_requests','order_status_logs','order_items','orders','table_sessions','menu_items','categories','device_pairings','devices','dining_tables'] as $table) Schema::dropIfExists($table);
    }
};
